config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#home'

  get '/about' , to: 'pages#about'

 resources :articles

 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title , presence: true , length: {minimum:3, maximum:20}
    validates :description , presence: true , length: {minimum:7, maximum:50}
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit,:update,:destroy,:show] 

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(get_allowed_params)
        if @article.save
            flash[:notice] = "The Article created successfully"
            redirect_to article_path(@article)
        else
            render :new
        end
    end
        
    def edit
    end

    def update
        if @article.update(get_allowed_params)
            flash[:notice] = "The Article updated successfully"
            redirect_to article_path(@article)
        else
            render :edit
        end
    end
    
    def index
        @articles = Article.all
    end
    
    def show
    end

    def destroy
        @article.destroy()
        flash[:notice] = "The Article was deleted Successfully"
        redirect_to articles_path
    end

    private 
        def set_article
            @article = Article.find(params[:id])
        end
        
        def get_allowed_params
            params.require(:article).permit(:title,:description)    
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end

    def about
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2> The following error prevented the method to create article </h2> 
<% @article.errors.full_messages.each do |err|%>
<%= err %>
<br>
<% end %>
<% end %>

<%= form_for @article do |f| %>
<p>
<%= f.label :title %>
<%= f.text_field :title %>
</p>
<p>
<%= f.label :description %>
<%= f.text_area  :description %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

<%= link_to 'Back to article listing' , articles_path %>

app/views/articles/edit.html.erb
<h2> Edit Existing article </h2>

<%= render 'form' %>

app/views/articles/index.html.erb
<h2> Showing all the articles </h2>
<p>
<%= link_to 'Create new article' , new_article_path %>
</p>
<% @articles.each do |article| %>
<p>
    <%= article.title %>
    <br>
    <%= article.description %>
    <br>
    <%= link_to 'show' , article_path(article) %>
    <br>
    <%= link_to 'edit' , edit_article_path(article) %>  
    <br>
    <%= link_to 'destroy' , article_path(article) , method: :delete , data: {confirm: "Are you sure you want to delete?"} %>  
    <br>
</p>
<% end %>

app/views/articles/new.html.erb
<h2> New </h2>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2> Showing the selected article </h2>

Title : <%= @article.title %>
<br>
Description : <%= @article.description %>
<br>

<br>
<%= link_to 'edit' , edit_article_path(@article) %>  
<br>
<%= link_to 'Back to article listing' , articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
    <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> ABOUT PAGE of blog_app </h1>

<%= link_to 'HOME' , root_path %>

app/views/pages/home.html.erb
<h1> HOME PAGE of blog_app </h1>
<%= link_to 'Blog App' , articles_path %> | <%= link_to 'ABOUT' , about_path %>